<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "konten".
 *
 * @property integer $id
 * @property string $judul
 * @property string $video
 * @property string $created_date
 * @property string $updated_date
 */
abstract class Konten extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'konten';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['judul', 'video', 'created_date', 'updated_date'], 'required'],
            [['created_date', 'updated_date'], 'safe'],
            [['judul'], 'string', 'max' => 100],
            [['video'], 'file', 'extensions' => 'mp4, avi, mov', 'maxSize' => 1024 * 1024 * 50], // Validasi file video

            // [['video'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'judul' => 'Judul',
            'video' => 'Video',
            'created_date' => 'Created Date',
            'updated_date' => 'Updated Date',
        ]);
    }
}
