<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "menu".
 *
 * @property integer $id
 * @property string $nama
 * @property string $deskripsi
 * @property string $gambar
 * @property integer $harga
 * @property string $created_date
 * @property string $update_date
 * @property string $aliasModel
 */
abstract class Menu extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'menu';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['nama', 'deskripsi', 'gambar', 'harga', 'created_date', 'update_date'], 'required'],
            [['deskripsi'], 'string'],
            [['harga'], 'integer'],
            [['created_date', 'update_date'], 'safe'],
            [['nama'], 'string', 'max' => 100],
            [['gambar'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'deskripsi' => 'Deskripsi',
            'gambar' => 'Gambar',
            'harga' => 'Harga',
            'created_date' => 'Created Date',
            'update_date' => 'Update Date',
        ];
    }




}
